### ISSUE TITLE
Add "About" page to docs

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/plopp#131]
We should add an "About Plopp" page, similar to, e.g., https://scipp.github.io/scippnexus/about/about.html. This should in particular list how to cite Plopp in publications.

**Comment by nvaytet** [comment]
More thnings to fix:

- I think I also want to rename the 'User guide' section to something else, like 'Basics' or 'Basic usage'.
Because all of the docs are a guide for the user, so it doesn't make sense to only have the first section as 'User guide'.

- The figure in the Superplot docs page only shows one line, instead of 3 coloured lines

**Comment by SimonHeybrock** [comment]
I suggest you create a new issue for this, so we can keep a single purpose for each task.

**Comment by nvaytet** [comment]
see #133
