### ISSUE TITLE
Non-interactive figures in HTML export of JupyterLab

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/plopp#150]
I get this, when opening the `html` after exporting to it from JupyterLab:

![image](https://user-images.githubusercontent.com/12912489/216064355-da2490aa-a783-4f2d-a162-38654e711fed.png)

Is this Matplotlib's fault, or ours?

**Comment by nvaytet** [comment]
Seems to work fine with raw Matplotlib figures:
![Screenshot at 2023-02-02 14-24-04](https://user-images.githubusercontent.com/39047984/216336856-af8192bc-602d-4ce1-b00a-923e16108c4d.png)

Probably something to do with the `mimebundle` representation?
Can you also show what the text says at the bottom, where you cropped? It seems it's talking about a 'bundle'?

**Comment by SimonHeybrock** [comment]
> Can you also show what the text says at the bottom, where you cropped? It seems it's talking about a 'bundle'?

This is unrelated text I wrote.

**Comment by nvaytet** [comment]
I'm also wondering if it's because of our svg repr. Do you also get the same if you make a figure with a lot of points, which gets converted to png?

**Comment by nvaytet** [comment]
@SimonHeybrock is this still an issue?

I tried in a notebook:
```Py
import plopp as pp
pp.data.data1d().plot()
```
then `Save and Export notebook as > HTML`, and it seems both svg and png figures show up properly in the html?

Only the `%matplotlib widget` figures are not showing properly, but I think that's always been the case? (instead of the figure, there is just text like `InteractiveFigure(children=(HBar(), HBar(children=(VBar(children=(Toolbar(children=(ButtonTool(icon='home', la…`)

**Comment by nvaytet** [comment]
I will close, feel free to re-open if it is still an issue.
