### ISSUE TITLE
Wrong unit on datetime axis

### ISSUE THREAD

**Issue by jokasimr** [scipp/plopp#255]
```python
import scipp as sc

sc.DataArray(
    coords={
        'x': sc.arange(
            'x',
            start=sc.datetime(0, unit='s'),
            stop=sc.datetime(int(1e9), unit='s'),
            step=sc.scalar(int(2e7), unit='s'),
        ),
    },
    data=sc.ones(dims=['x'], shape=[50])
).plot()
```
![Screenshot from 2023-09-21 13-11-11](https://github.com/scipp/plopp/assets/20954731/2e24033f-148f-48e9-9f98-c1cd6cd841da)

The numbers on the x-axis correspond to years, but the displayed unit is "[s]".

**Comment by jokasimr** [comment]
Maybe not important, I think this only happens for `datetime` coordinates.

**Comment by nvaytet** [comment]
Maybe a difficult one to solve? The unit you specified when creating the variable is actually `s`.
WIth datetimes, it is what defines the resolution you want to have in your datetimes.

You only know the axis should be labeled as `[year]` because of the range you are using.

Say I use the same example you gave, but instead of spanning many years, it spans only a few seconds or minutes.
```Py
import scipp as sc

x = sc.arange(
            'x',
            start=sc.datetime(0, unit='s'),
            stop=sc.datetime(int(33), unit='s'))

sc.DataArray(
    coords={
        'x': sc.arange(
            'x',
            start=sc.datetime(0, unit='s'),
            stop=sc.datetime(int(33), unit='s'),
            # step=sc.scalar(int(2e7), unit='s'),
        ),
    },
    data=sc.ones(sizes=x.sizes)
).plot()
```
![Screenshot at 2023-09-22 10-30-46](https://github.com/scipp/plopp/assets/39047984/d404340c-836b-4fb9-bca8-6888955f44a2)

What should the axis be labeled as now?

I agree that it is confusing to have `[s]` on your example above. Maybe the solution would be to not show a unit when using datetime coords?

Part of the confusing thing in your figure above is that the horizontal axis is labeled `x`. If that coordinate was named `year`, then it would be more clear. And so having `year` instead of `year [s]` would be even better?

**Comment by jokasimr** [comment]
I think you're right it is difficult to solve. It is probably not good to not show any unit when displaying a datetime axis. In my example above the axis would then just say `x` with some numbers without any indication that the numbers are actually years.

Another option would be to change the displayed unit to `[datetime]`, that would cover both the case when displaying years and then displaying seconds like what you showed.

**Comment by nvaytet** [comment]
> Another option would be to change the displayed label to x [datetime]

I think this would also be confusing because `datetime` is not a physical unit, per se.

**Comment by nvaytet** [comment]
I'm starting to think that `x [datetime]` is probably the best suggestion so far.
