### ISSUE TITLE
Add polar plot functionality

### ISSUE THREAD

**Issue by TheFermiSea** [scipp/plopp#288]
Currently, I have to convert everything into numpy arrays and use basic Matplotlib methods to generate polar plots, which strips away the awesome features in Plopp/Scipp.  How easy/hard would this be to add (including unit detection, error bars, etc)?  Maybe just a kwarg like is done in plt.subplots(subplot_kw={'projection':'polar'})?  It isn't too burdensome right now, but makes my code more messy/less readable for students.

**Comment by nvaytet** [comment]
Hi there, should definitely be possible. The plan was always to add more plot types as we go along.
Could you just send a small example of the plots you are making right know so we know what to aim for?
(just an example with the conversion to numpy and then calling matplotlib)

**Comment by nvaytet** [comment]
I feel that having a dedicated function is cleaner than having a keyword argument, because if we continue to add more and more keyword args, then the interface to the `plot` function will become impossible to maintain.

So i'm thinking something like `polarplot()`, or even just `polar()`

**Comment by TheFermiSea** [comment]
MWE in matplotlib would be something like this:

`fig, ax = plt.subplots(subplot_kw={'projection':'polar'})
ax.plot(da.coords['alpha'].values,da.values)`

where `da.coords['alpha'].unit = sc.units.rad` 

Obviously this completely removes all scipp/plopp functionality

**Comment by nvaytet** [comment]
See #296

**Comment by nvaytet** [comment]
The naive implementation of the polar plot would have been to make a small function, e.g. `plopp.polar()` that would internally just create some polar Matplotlib axes and then call `pp.plot(data, ax=some_polar_axes)`.

However, we would be inserting Matplotlib specifics in the top level functions of Plopp.
It wouldn't work with a different backend (e.g. `plotly`).
So the not-so-naive implementation resulted in quite a few changes in #296.

Looking at all the added complexity, additions to backends, special limits handling, different available attributes depending on the axes projection, I don't really feel like adding all those changes in, for a result that still doesn't look great.
For instance, there is still a unit of radians [rad] placed on one of the axes, which doesn't make much sense because the numbers on the ticks are in degrees.
We would have to have an overload to the view `update` function which would remove the unit of the coord so that the unit doesn't show on the axes.

@TheFermiSea you mention that you are losing a lot of the plotting functionality by having to go through numpy and raw mpl, but I am not so sure how much is really lost?
I propose an alternative method in #298 which is to use a mix of matplotlib and plopp, creating the polar axes with mpl and passing them to plopp.
Even interactive plots should still be doable using this method.

Does that sound reasonable?
